server:
  port: 8081

### Spring Properties
spring:
  application:
    name: hibernate-soft-delete

  # SQL Server datasource Properties
  datasource:
    url: jdbc:mysql://localhost:3306/hibernate-soft-delete
    username: root
    password: Test#12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA properties
  jpa:
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: update
        show_sql: false
        format_sql: false